# Homework 1: Introduction to Machine Learning

Red Meigen Importante

In [1]:
import numpy as np
import pandas as pd

## Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

## Getting the data

In [3]:
df = pd.read_csv('data/car_fuel_efficiency_2026.csv')

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## Q2. Records count

How many records are in the dataset?

In [4]:
len(df)

10000

## Q3. Fuel types

How many fuel types are presented in the dataset?

In [5]:
df['fuel_type'].nunique()

3

## Q4. Missing values

How many columns in the dataset have missing values?

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [7]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

## Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.

In [8]:
df['horsepower'].median()

np.float64(254.0)

2. Next, calculate the most frequent value of the same horsepower column.

In [9]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [10]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

4. Now, calculate the median value of horsepower once again.

In [11]:
df['horsepower'].median()

np.float64(252.0)

**Question:** Has it changed?

**Answer:** Yes, it decreased

## Q7. Sum of weights

1. Select all the cars from Asia

In [12]:
asian_cars = df[df['origin'] == 'Asia']

asian_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

2. Select only columns `vehicle_weight` and `model_year`

In [13]:
asian_cars = asian_cars[['vehicle_weight', 'model_year']]

asian_cars.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

3. Select the first 7 values

In [14]:
asian_cars = asian_cars.head(7)

asian_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

4. Get the underlying NumPy array. Let's call it `X`.

In [15]:
X = asian_cars.values

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [17]:
X.shape

(7, 2)

In [19]:
X.T.shape

(2, 7)

In [20]:
XTX = np.dot(X.T, X)

print(XTX)
print(XTX.shape)

[[131950500  60750580]
 [ 60750580  28041424]]
(2, 2)

6. Invert `XTX`.

In [21]:
XTX_inv = np.linalg.inv(XTX)

print(XTX_inv)
print(XTX_inv.shape)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
(2, 2)

7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [22]:
w = XTX_inv.dot(X.T).dot(y)
print(w)

[0.13644777 0.2327492 ]

9. What's the sum of all the elements of the result?

In [24]:
np.sum(w)

np.float64(0.36919696904925486)

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson